services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: feature_toggle_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: feature_toggle_db
      DATABASE_USER: username
      DATABASE_PASSWORD: password
      NODE_ENV: production
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
